/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stream a chat reply as Server-Sent Events
         * @description Accepts a student message and streams SSE events.
         *     Each `data:` line is a JSON object with `type` of `chunk`, `done`, or `error`.
         */
        post: operations["streamChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            /** @example VALIDATION_ERROR */
            code: string;
            message: string;
            /** @default [] */
            details: unknown[];
        };
        SuccessEnvelope: {
            /** @enum {boolean} */
            success: true;
            data: Record<string, never>;
            error: Record<string, never> | null;
            meta: {
                [key: string]: unknown;
            };
        };
        ErrorEnvelope: {
            /** @enum {boolean} */
            success: false;
            data: unknown;
            error: components["schemas"]["ApiError"];
            meta: {
                [key: string]: unknown;
            };
        };
        HealthData: {
            /** @example healthy */
            status: string;
        };
        HealthResponse: components["schemas"]["SuccessEnvelope"] & {
            data?: components["schemas"]["HealthData"];
        };
        ChatRequest: {
            /**
             * Format: uuid
             * @description Tenant UUID (temporary until JWT claims; S18).
             */
            tenant_id: string;
            /**
             * Format: uuid
             * @description Check-in session UUID.
             */
            session_id: string;
            /** @description Student message text. */
            message: string;
        };
        ChatSseChunkEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ChatSseChunkEvent";
            data: string;
        };
        ChatSseDoneEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ChatSseDoneEvent";
            guardrail_triggered: boolean;
            /** @enum {string|null} */
            guardrail_category?: "critical" | "dropout" | "depression" | null;
            weekly_tasks?: string[] | null;
        };
        ChatSseErrorEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ChatSseErrorEvent";
            message: string;
        };
        ChatSseEvent: components["schemas"]["ChatSseChunkEvent"] | components["schemas"]["ChatSseDoneEvent"] | components["schemas"]["ChatSseErrorEvent"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    streamChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description SSE stream of chat events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
